import { useNavigate } from 'react-router-dom';
import { CalendarClock, AlertTriangle, FileSignature, Coins, Ticket, WifiOff, MapPin, Store, ScrollText } from 'lucide-react';
import { dashboardService } from '../../services/amcService.js';
import { useQuery } from '../../hooks/useQuery.js';
import { useAuth, useRights } from '../../app/AuthContext.jsx';
import { Kpi, Badge, ErrorBox } from '../../components/ui/Controls.jsx';
import { Expiry } from '../customers/CustomersPage.jsx';
import { PrioBadge, Sla } from '../tickets/ticketUi.jsx';
import { formatDate, today, formatAED, rel, displayMobile } from '../../lib/fmt.js';
const Card = ({ title, icon: Icon, action, children, count }) => <section className="card flex flex-col"><div className="flex items-center justify-between border-b border-line px-4 py-2.5"><span className="inline-flex items-center gap-2 text-[12.5px] font-semibold uppercase tracking-wide text-muted">{Icon && <Icon className="h-3.5 w-3.5" />}{title}{count != null && <span className="badge bg-surface-3 text-muted">{count}</span>}</span>{action}</div><div className="flex-1">{children}</div></section>;
const Row = ({ onClick, children }) => <button onClick={onClick} className="flex w-full items-center gap-3 border-b border-line/60 px-4 py-2 text-left text-[13px] last:border-0 hover:bg-accent/[.06]">{children}</button>;
const Empty = ({ text }) => <div className="px-4 py-6 text-center text-[12.5px] text-faint">{text}</div>;
/** Dashboard: expiring in 30 days, expired, outstanding, open tickets by priority, servers offline, today's visits. */
export function DashboardPage() {
  const { session } = useAuth(); const { money } = useRights(); const nav = useNavigate(); const q = useQuery(() => dashboardService.snapshot(), []); const d = q.data; const k = d?.kpi || {};
  const hour = new Date().getHours(); const greet = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening';
  const prio = (p) => Number(d?.byPriority?.find((x) => x.PRIORITY === p)?.N || 0); const openTickets = (d?.byPriority || []).reduce((a, x) => a + Number(x.N), 0);
  return <div className="w-full">
    <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-[22px] font-semibold tracking-tight">{greet}, {session?.user?.USER_NAME?.split(' ')[0]}</h1><p className="mt-0.5 text-[12px] text-muted">DataCare AMC · {formatDate(today())} · {k.SHOPS ?? '…'} shops on {k.SERVERS ?? '…'} servers</p></div></div>
    <ErrorBox error={q.error} />
    <div className="mb-4 grid gap-2 sm:grid-cols-3 xl:grid-cols-6">
      <Kpi label="Licences ending in 30 d" value={k.LIC_30 ?? '…'} icon={CalendarClock} tone={k.LIC_30 ? 'text-warn' : ''} onClick={() => nav('/reports/expiring-licences')} /><Kpi label="Licences expired" value={k.LIC_EXPIRED ?? '…'} icon={AlertTriangle} tone={k.LIC_EXPIRED ? 'text-bad' : ''} onClick={() => nav('/customers?expiry=expired')} />
      <Kpi label="AMCs ending in 30 d" value={k.AMC_30 ?? '…'} sub={`${k.AMC_LIVE ?? 0} live · ${k.NO_AMC ?? 0} shops without`} icon={FileSignature} tone={k.AMC_30 ? 'text-warn' : ''} onClick={() => nav('/reports/expiring-amcs')} />
      {money ? <Kpi label="Outstanding" value={formatAED(k.OUTSTANDING || 0)} sub={Number(k.OVERDUE) ? `${formatAED(k.OVERDUE)} overdue` : 'nothing overdue'} icon={Coins} tone={Number(k.OUTSTANDING) ? 'text-bad' : ''} onClick={() => nav('/outstanding')} /> : <Kpi label="Shops" value={k.SHOPS ?? '…'} icon={Store} onClick={() => nav('/customers')} />}
      <Kpi label="Open tickets" value={openTickets} sub={`${prio('URGENT')} urgent · ${prio('HIGH')} high · ${k.TICKETS_LATE || 0} past SLA`} icon={Ticket} tone={prio('URGENT') ? 'text-bad' : openTickets ? 'text-warn' : ''} onClick={() => nav('/tickets')} />
      <Kpi label="Servers offline" value={k.SERVERS_OFFLINE ?? '…'} sub="no heartbeat for 48 h" icon={WifiOff} tone={k.SERVERS_OFFLINE ? 'text-bad' : 'text-ok'} onClick={() => nav('/servers')} />
    </div>
    <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">
      <Card title="Licences ending soon" icon={CalendarClock} count={d?.expiring?.length} action={<button className="text-[12px] text-accent hover:underline" onClick={() => nav('/reports/expiring-licences')}>Report</button>}>{d?.expiring?.length ? d.expiring.map((c) => <Row key={c.CUST_ID} onClick={() => nav(`/customers/${c.CUST_ID}`)}><div className="min-w-0 flex-1"><div className="truncate font-medium">{c.SHOP_NAME}</div><div className="text-[11.5px] text-muted">{c.CONTACT_NAME || c.SHOP_CODE}{c.MOBILE_NO ? ` · ${displayMobile(c.MOBILE_NO)}` : ''}{c.AMC_NO ? '' : ' · no AMC'}</div></div><Expiry date={c.LIC_END} days={c.DAYS_LEFT} /></Row>) : <Empty text="Nothing ends in the next 30 days" />}</Card>
      <Card title="Open tickets" icon={Ticket} count={openTickets} action={<button className="text-[12px] text-accent hover:underline" onClick={() => nav('/tickets')}>All</button>}>{d?.tickets?.length ? d.tickets.map((t) => <Row key={t.TICKET_ID} onClick={() => nav(`/tickets?open=${t.TICKET_ID}`)}><PrioBadge p={t.PRIORITY} /><div className="min-w-0 flex-1"><div className="truncate font-medium normal-case">{t.TITLE}</div><div className="text-[11.5px] text-muted">{t.TICKET_NO} · {t.SHOP_NAME} · {t.ASSIGNED_NAME || 'unassigned'}</div></div><Sla t={t} /></Row>) : <Empty text="No open tickets" />}</Card>
      <Card title="Today's visits" icon={MapPin} count={d?.visitsToday?.length} action={<button className="text-[12px] text-accent hover:underline" onClick={() => nav('/visits')}>Calendar</button>}>{d?.visitsToday?.length ? d.visitsToday.map((v) => <Row key={v.VISIT_ID} onClick={() => nav('/visits')}><span className="num w-12 text-muted">{v.VISIT_TIME || '—'}</span><div className="min-w-0 flex-1"><div className="truncate font-medium">{v.SHOP_NAME}</div><div className="truncate text-[11.5px] normal-case text-muted">{v.PURPOSE} · {v.ENGINEER_NAME || 'no engineer'}</div></div><Badge tone={v.STATUS === 'DONE' ? 'ok' : 'info'}>{v.STATUS}</Badge></Row>) : <Empty text="No visits today" />}</Card>
      {money && <Card title="Overdue invoices" icon={Coins} count={d?.overdue?.length} action={<button className="text-[12px] text-accent hover:underline" onClick={() => nav('/outstanding')}>Outstanding</button>}>{d?.overdue?.length ? d.overdue.map((i) => <Row key={i.INV_ID} onClick={() => nav(`/customers/${i.CUST_ID}?tab=payments`)}><div className="min-w-0 flex-1"><div className="truncate font-medium">{i.SHOP_NAME}</div><div className="text-[11.5px] text-muted">{i.INV_NO} · due {formatDate(i.DUE_DATE)}{i.DAYS_OVERDUE > 0 ? ` · ${i.DAYS_OVERDUE} d over` : ''}</div></div><span className={`num font-semibold ${i.DAYS_OVERDUE > 0 ? 'text-bad' : ''}`}>{formatAED(i.BALANCE)}</span></Row>) : <Empty text="Nothing outstanding" />}</Card>}
      <Card title="Servers offline" icon={WifiOff} count={d?.offline?.length} action={<button className="text-[12px] text-accent hover:underline" onClick={() => nav('/servers')}>Servers</button>}>{d?.offline?.length ? d.offline.map((s) => <Row key={s.SERVER_ID} onClick={() => nav('/servers')}><div className="min-w-0 flex-1"><div className="truncate font-medium">{s.NAME}</div><div className="text-[11.5px] text-muted">{s.SERVER_CODE} · {s.SHOPS} shops</div></div><span className="text-[12px] text-bad">{s.LAST_HEARTBEAT ? `last ${rel(s.LAST_HEARTBEAT)}` : 'never seen'}</span></Row>) : <Empty text="Every server reported within 48 hours" />}</Card>
      <Card title="Recent activity" icon={ScrollText}>{d?.activity?.length ? d.activity.map((a, i) => <div key={i} className="flex items-center gap-3 border-b border-line/60 px-4 py-2 text-[12.5px] last:border-0"><span className="w-16 shrink-0 text-muted">{rel(a.LOG_TIME)}</span><span className="min-w-0 flex-1 truncate"><span className="font-medium">{a.USER_NAME || 'System'}</span> <span className="text-muted">{a.ACTION.toLowerCase()}</span> {a.TABLE_NAME.replace('AMC_', '').toLowerCase()} {a.REC_KEY}</span></div>) : <Empty text="Nothing yet" />}</Card>
    </div>
  </div>;
}
