import { useState } from 'react';
import { Plus, Play, Eye, MessageCircle, Mail, Send, Trash2, BellRing } from 'lucide-react';
import { reminderService } from '../../services/amcService.js';
import { useQuery } from '../../hooks/useQuery.js';
import { PageHeader, Badge, Tabs, Toggle, ConfirmDialog, ErrorBox } from '../../components/ui/Controls.jsx';
import { Dropdown } from '../../components/ui/Dropdown.jsx';
import { DataTable, Pager } from '../../components/ui/DataTable.jsx';
import { Button } from '../../components/ui/Button.jsx';
import { Modal } from '../../components/ui/Modal.jsx';
import { Input, Select, Textarea } from '../../components/ui/Field.jsx';
import { useToast } from '../../components/ui/Toast.jsx';
import { formatDateTime, rel } from '../../lib/fmt.js';
const KINDS = [['LIC_EXPIRY', 'Licence expiry'], ['AMC_EXPIRY', 'AMC expiry'], ['PAY_OVERDUE', 'Payment overdue'], ['TICKET_OVERDUE', 'Ticket past SLA']];
const kindLabel = (k) => KINDS.find((x) => x[0] === k)?.[1] || k;
const whenText = (r) => r.KIND === 'PAY_OVERDUE' ? `${r.DAYS} d after due` : r.KIND === 'TICKET_OVERDUE' ? `${r.DAYS} h past SLA` : r.DAYS === 0 ? 'on the day' : `${r.DAYS} d before`;
const VARS = { LIC_EXPIRY: '{shop} {contact} {date} {days}', AMC_EXPIRY: '{shop} {contact} {date} {days} {no}', PAY_OVERDUE: '{shop} {contact} {date} {no} {amount}', TICKET_OVERDUE: '{shop} {no} {title} {date}' };
/** Reminders: the rules (what, when, channel, template), what is due right now, run now, the log of what went out, a test message. */
export function RemindersPage() {
  const toast = useToast(); const [tab, setTab] = useState('rules'); const rules = useQuery(() => reminderService.rules(), []); const rows = rules.data?.rows || [];
  const [edit, setEdit] = useState(null); const [ask, setAsk] = useState(null); const [busy, setBusy] = useState(''); const [due, setDue] = useState(null); const [test, setTest] = useState(null);
  const [page, setPage] = useState(1); const [lf, setLf] = useState({ kind: '', ok: '' }); const log = useQuery(() => reminderService.log({ page, ...lf }), [page, lf, tab], { enabled: tab === 'log' });
  const save = async () => { setBusy('save'); try { await reminderService.saveRule(edit); setEdit(null); rules.refetch(); toast('Rule saved', 'success'); } catch (e) { toast(e.message, 'warn'); } finally { setBusy(''); } };
  const remove = async () => { try { await reminderService.removeRule(ask.RULE_ID); setAsk(null); rules.refetch(); toast('Rule removed', 'success'); } catch (e) { toast(e.message, 'error'); } };
  const preview = async () => { setBusy('due'); try { setDue((await reminderService.due()).rows); } catch (e) { toast(e.message, 'error'); } finally { setBusy(''); } };
  const run = async (ruleId) => { setBusy('run'); try { const r = await reminderService.run({ ruleId }); toast(`${r.sent} sent, ${r.failed} failed of ${r.due} due`, r.failed ? 'warn' : 'success', 6000); rules.refetch(); setDue(null); setTab('log'); } catch (e) { toast(e.message, 'error'); } finally { setBusy(''); } };
  const sendTest = async () => { setBusy('test'); try { const r = await reminderService.test(test); toast(r.ok ? `Sent: ${r.answer}` : `Not sent: ${r.answer}`, r.ok ? 'success' : 'warn', 8000); setTest(null); } catch (e) { toast(e.message, 'error'); } finally { setBusy(''); } };
  const d = rules.data;
  return <div className="w-full">
    <PageHeader title="Reminders" subtitle="Licence expiry 30 / 15 / 7 / 0 days, AMC expiry, payment overdue and tickets past SLA — by WhatsApp (DataCare Chat) and e-mail. Each rule fires once per customer and reference, so a missed day still goes out the next." actions={<><Button variant="ghost" icon={Eye} loading={busy === 'due'} onClick={preview}>What is due</Button><Button variant="ghost" icon={Send} onClick={() => setTest({ channel: 'WA', to: '' })}>Test message</Button><Button icon={Play} loading={busy === 'run'} onClick={() => run(null)}>Run now</Button></>} />
    {d && <div className="mb-3 flex flex-wrap items-center gap-3 text-[12.5px] text-muted"><span className="inline-flex items-center gap-1"><MessageCircle className="h-3.5 w-3.5" />WhatsApp <Badge tone={d.wa ? 'ok' : 'bad'}>{d.wa ? 'ready' : 'not set up'}</Badge></span><span className="inline-flex items-center gap-1"><Mail className="h-3.5 w-3.5" />E-mail <Badge tone={d.mail ? 'ok' : 'bad'}>{d.mail ? 'ready' : 'not set up'}</Badge></span><span>Daily at {d.settings?.time} Dubai</span><span>Last run {d.lastRun?.at ? `${rel(d.lastRun.at)} — ${d.lastRun.sent} sent, ${d.lastRun.failed} failed` : 'never'}</span></div>}
    <ErrorBox error={rules.error} />
    <div className="mb-3"><Tabs value={tab} onChange={setTab} tabs={[{ value: 'rules', label: 'Rules', count: rows.length }, { value: 'log', label: 'Sent log' }]} /></div>
    {tab === 'rules' && <div className="space-y-3">
      <div className="flex justify-end"><Button icon={Plus} onClick={() => setEdit({ KIND: 'LIC_EXPIRY', DAYS: 30, CHANNELS: 'WA,EMAIL', TEMPLATE: '', TO_TEAM: false, ACTIVE: true })}>New rule</Button></div>
      <DataTable rows={rows} loading={rules.loading} rowKey="RULE_ID" onRowClick={(r) => setEdit({ ...r })} columns={[{ key: 'KIND', label: 'What', primary: true, render: (r) => <span className="font-medium">{kindLabel(r.KIND)}</span> }, { key: 'DAYS', label: 'When', render: whenText }, { key: 'CHANNELS', label: 'Channels', render: (r) => r.CHANNELS.split(',').map((c) => <Badge key={c} tone={c === 'WA' ? 'ok' : 'info'} className="mr-1">{c === 'WA' ? 'WhatsApp' : 'E-mail'}</Badge>) }, { key: 'TO_TEAM', label: 'Also the team', align: 'center', render: (r) => r.TO_TEAM ? 'Yes' : '—' }, { key: 'TEMPLATE', label: 'Message', render: (r) => <span className="block max-w-[420px] truncate normal-case text-muted">{r.TEMPLATE || '(default text)'}</span> }, { key: 'ACTIVE', label: 'Status', render: (r) => <Badge tone={r.ACTIVE ? 'ok' : 'muted'}>{r.ACTIVE ? 'On' : 'Off'}</Badge> }, { key: 'A', label: '', render: (r) => <span className="flex justify-end gap-1" onClick={(e) => e.stopPropagation()}><button className="btn-ghost !h-7 !px-2 !text-[12px]" title="Run only this rule" onClick={() => run(r.RULE_ID)}><Play className="h-3.5 w-3.5" /></button><button className="btn-ghost !h-7 !px-2 !text-bad" onClick={() => setAsk(r)}><Trash2 className="h-3.5 w-3.5" /></button></span> }]} emptyTitle="No rules" />
      {due && <section className="card"><div className="flex items-center justify-between border-b border-line px-4 py-2.5"><span className="text-[13px] font-semibold">Due right now — {due.length} message{due.length === 1 ? '' : 's'}</span><Button variant="ghost" onClick={() => setDue(null)}>Hide</Button></div><DataTable rows={due} rowKey={(r) => r} columns={[{ key: 'KIND', label: 'Rule', render: (r) => `${kindLabel(r.KIND)} · ${whenText(r)}` }, { key: 'SHOP_NAME', label: 'Shop', primary: true }, { key: 'REF_KEY', label: 'Ref' }, { key: 'CHANNEL', label: 'Via', render: (r) => r.CHANNEL === 'WA' ? 'WhatsApp' : 'E-mail' }, { key: 'SENT_TO', label: 'To', render: (r) => <span className="normal-case">{r.SENT_TO || <span className="text-bad">missing on customer</span>}</span> }, { key: 'MESSAGE', label: 'Message', render: (r) => <span className="block max-w-[420px] truncate normal-case text-muted" title={r.MESSAGE}>{r.MESSAGE}</span> }].map((c, i) => ({ ...c, key: c.key || String(i) }))} emptyTitle="Nothing due" /></section>}
    </div>}
    {tab === 'log' && <div className="space-y-3"><div className="flex flex-wrap gap-2"><Dropdown size="sm" className="w-44" value={lf.kind} onChange={(e) => { setLf({ ...lf, kind: e.target.value }); setPage(1); }} options={[['', 'Any kind'], ...KINDS, ['TEST', 'Test']]} /><Dropdown size="sm" className="w-36" value={lf.ok} onChange={(e) => { setLf({ ...lf, ok: e.target.value }); setPage(1); }} options={[['', 'Sent and failed'], ['1', 'Sent'], ['0', 'Failed']]} /></div>
      <DataTable rows={log.data?.rows || []} loading={log.loading} rowKey="LOG_ID" columns={[{ key: 'SENT_AT', label: 'When', render: (r) => <span className="num whitespace-nowrap">{formatDateTime(r.SENT_AT)}</span> }, { key: 'KIND', label: 'Kind', render: (r) => kindLabel(r.KIND) }, { key: 'SHOP_NAME', label: 'Shop', primary: true, render: (r) => r.SHOP_NAME || '—' }, { key: 'REF_KEY', label: 'Ref' }, { key: 'CHANNEL', label: 'Via', render: (r) => r.CHANNEL === 'WA' ? 'WhatsApp' : 'E-mail' }, { key: 'SENT_TO', label: 'To', render: (r) => <span className="normal-case">{r.SENT_TO || '—'}</span> }, { key: 'OK', label: 'Result', render: (r) => <span className="inline-flex items-center gap-1.5"><Badge tone={r.OK ? 'ok' : 'bad'}>{r.OK ? 'Sent' : 'Failed'}</Badge><span className="max-w-[260px] truncate normal-case text-[11.5px] text-muted" title={r.RESULT || ''}>{r.RESULT}</span></span> }, { key: 'USER_NAME', label: 'By', hideBelow: 'lg', render: (r) => r.USER_NAME || 'scheduler' }]} emptyTitle="Nothing sent yet" footer={<Pager page={page} pageSize={50} total={log.data?.total || 0} onPage={setPage} />} /></div>}
    <Modal open={!!edit} onClose={() => setEdit(null)} title={edit?.RULE_ID ? 'Edit rule' : 'New rule'} size="md" footer={<><Button variant="ghost" onClick={() => setEdit(null)}>Cancel</Button><Button loading={busy === 'save'} onClick={save}>Save rule</Button></>}>
      {edit && <div className="grid gap-3 sm:grid-cols-2"><Select label="What" value={edit.KIND} onChange={(e) => setEdit({ ...edit, KIND: e.target.value })} options={KINDS} /><Input label={edit.KIND === 'PAY_OVERDUE' ? 'Days after the due date' : edit.KIND === 'TICKET_OVERDUE' ? 'Hours past the SLA' : 'Days before expiry (0 = the day)'} type="number" min="0" value={edit.DAYS} onChange={(e) => setEdit({ ...edit, DAYS: e.target.value })} />
        <div className="rounded-md border border-line bg-surface-2/50 px-4 py-1 sm:col-span-2"><Toggle label="WhatsApp" checked={edit.CHANNELS.includes('WA')} onChange={(v) => setEdit({ ...edit, CHANNELS: [v && 'WA', edit.CHANNELS.includes('EMAIL') && 'EMAIL'].filter(Boolean).join(',') })} /><Toggle label="E-mail" checked={edit.CHANNELS.includes('EMAIL')} onChange={(v) => setEdit({ ...edit, CHANNELS: [edit.CHANNELS.includes('WA') && 'WA', v && 'EMAIL'].filter(Boolean).join(',') })} /><Toggle label="Also tell the DataCare team" hint="To the team number / e-mail in Settings → SLA & reminders" checked={edit.TO_TEAM} onChange={(v) => setEdit({ ...edit, TO_TEAM: v })} /><Toggle label="Active" checked={edit.ACTIVE} onChange={(v) => setEdit({ ...edit, ACTIVE: v })} /></div>
        <Textarea label="Message" className="sm:col-span-2" rows={4} value={edit.TEMPLATE || ''} onChange={(e) => setEdit({ ...edit, TEMPLATE: e.target.value })} hint={`Blank = the standard text. Placeholders: ${VARS[edit.KIND]}`} /></div>}
    </Modal>
    <Modal open={!!test} onClose={() => setTest(null)} title="Send a test message" size="sm" footer={<><Button variant="ghost" onClick={() => setTest(null)}>Cancel</Button><Button loading={busy === 'test'} onClick={sendTest}>Send</Button></>}>{test && <div className="space-y-3"><Select label="Channel" value={test.channel} onChange={(e) => setTest({ ...test, channel: e.target.value })} options={[['WA', 'WhatsApp'], ['EMAIL', 'E-mail']]} /><Input label={test.channel === 'WA' ? 'Mobile' : 'E-mail'} upper={false} autoFocus value={test.to} onChange={(e) => setTest({ ...test, to: e.target.value })} onKeyDown={(e) => e.key === 'Enter' && sendTest()} /></div>}</Modal>
    <ConfirmDialog open={!!ask} onClose={() => setAsk(null)} onConfirm={remove} title="Remove this rule?" message={`${kindLabel(ask?.KIND)} · ${ask ? whenText(ask) : ''}. The log of what it sent stays.`} confirmLabel="Remove" />
  </div>;
}
