-- DcAmc : DataCare's own AMC book. ONE database, DcNext-style names (UPPERCASE_UNDERSCORE).
-- Scripts are numbered and idempotent; SCHEMA_VER remembers which ran (Field update applies the rest).
IF OBJECT_ID('SCHEMA_VER') IS NULL
CREATE TABLE SCHEMA_VER (SCRIPT_NAME VARCHAR(200) PRIMARY KEY, APPLY_DATE DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
-- settings, one row per key (company details, numbering, VAT %, SMTP, WhatsApp, backup…); secrets are AES-encrypted values
IF OBJECT_ID('APP_SET') IS NULL
CREATE TABLE APP_SET (SET_KEY VARCHAR(60) PRIMARY KEY, SET_VALUE NVARCHAR(MAX) NULL, EDIT_DATE DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
-- DcAMC's own logins (the ERP's master logins are NOT these)
IF OBJECT_ID('AMC_USER') IS NULL
CREATE TABLE AMC_USER (
  USER_ID      INT IDENTITY(1,1) PRIMARY KEY,
  LOGIN_NAME   NVARCHAR(50)  NOT NULL UNIQUE,
  USER_NAME    NVARCHAR(100) NOT NULL,
  LOGIN_PWD    VARCHAR(100)  NOT NULL,              -- bcrypt
  ROLE         VARCHAR(10)   NOT NULL DEFAULT 'SUPPORT',   -- OWNER | ACCOUNTS | SUPPORT
  MOBILE_NO    VARCHAR(20)   NULL,
  EMAIL_ID     NVARCHAR(150) NULL,
  ACTIVE       BIT           NOT NULL DEFAULT 1,
  CHANGE_PWD   BIT           NOT NULL DEFAULT 0,
  FAIL_COUNT   INT           NOT NULL DEFAULT 0,
  LOCK_UNTIL   DATETIME2     NULL,
  TOTP_SECRET  VARCHAR(100)  NULL,                  -- optional authenticator app
  TOTP_ON      BIT           NOT NULL DEFAULT 0,
  LAST_LOGIN   DATETIME2     NULL,
  ENTRY_DATE   DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  EDIT_DATE    DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF OBJECT_ID('USER_SESSION') IS NULL
CREATE TABLE USER_SESSION (
  SESSION_ID  VARCHAR(64) PRIMARY KEY,
  USER_ID     INT NOT NULL,
  IP_ADDR     VARCHAR(64) NULL,
  USER_AGENT  NVARCHAR(300) NULL,
  START_TIME  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  LAST_TIME   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  END_TIME    DATETIME2 NULL,
  END_REASON  VARCHAR(20) NULL
);
GO
IF OBJECT_ID('LOGIN_LOG') IS NULL
CREATE TABLE LOGIN_LOG (LOG_ID BIGINT IDENTITY(1,1) PRIMARY KEY, USER_ID INT NULL, LOGIN_NAME NVARCHAR(50) NULL, RESULT VARCHAR(20) NOT NULL, IP_ADDR VARCHAR(64) NULL, USER_AGENT NVARCHAR(300) NULL, LOG_TIME DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
-- every write: who, when, table, key, action, detail. Nothing in the app may switch this off.
IF OBJECT_ID('AUDIT_LOG') IS NULL
CREATE TABLE AUDIT_LOG (LOG_ID BIGINT IDENTITY(1,1) PRIMARY KEY, USER_ID INT NULL, TABLE_NAME VARCHAR(40) NOT NULL, REC_KEY VARCHAR(60) NULL, ACTION VARCHAR(20) NOT NULL, DETAIL NVARCHAR(MAX) NULL, LOG_TIME DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AUDIT_LOG_TIME') CREATE INDEX IX_AUDIT_LOG_TIME ON AUDIT_LOG (LOG_TIME DESC);
GO
