-- Contracts, tax invoices and payments. Money is AED, VAT 5 % unless the contract says otherwise.
IF OBJECT_ID('AMC_CONTRACT') IS NULL
CREATE TABLE AMC_CONTRACT (
  CONTRACT_ID     INT IDENTITY(1,1) PRIMARY KEY,
  CUST_ID         INT           NOT NULL,
  CONTRACT_NO     VARCHAR(20)   NOT NULL UNIQUE,      -- AMC-00001
  START_DATE      DATE          NOT NULL,
  END_DATE        DATE          NOT NULL,             -- start + 365 days
  AMOUNT          DECIMAL(18,2) NOT NULL DEFAULT 0,
  VAT_PRC         DECIMAL(5,2)  NOT NULL DEFAULT 5,
  VAT_AMT         DECIMAL(18,2) NOT NULL DEFAULT 0,
  TOTAL           DECIMAL(18,2) NOT NULL DEFAULT 0,
  COVERS_SUPPORT  BIT           NOT NULL DEFAULT 1,
  COVERS_UPDATES  BIT           NOT NULL DEFAULT 1,
  VISITS_INCLUDED INT           NOT NULL DEFAULT 0,
  TILLS           INT           NULL,                 -- pushed to the licence when set
  PLAN_CODE       VARCHAR(20)   NULL,
  STATUS          VARCHAR(10)   NOT NULL DEFAULT 'DRAFT',   -- DRAFT | LIVE | EXPIRED | CANCELLED
  RENEWED_FROM    INT           NULL,
  PUSH_STATUS     VARCHAR(10)   NULL,                 -- PENDING | DONE | FAILED
  PUSH_MSG        NVARCHAR(500) NULL,
  PUSH_AT         DATETIME2     NULL,
  REMARK          NVARCHAR(1000) NULL,
  USER_ID         INT           NULL,
  ENTRY_DATE      DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  EDIT_DATE       DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AMC_CONTRACT_CUST') CREATE INDEX IX_AMC_CONTRACT_CUST ON AMC_CONTRACT (CUST_ID, END_DATE DESC);
GO
IF OBJECT_ID('AMC_INVOICE') IS NULL
CREATE TABLE AMC_INVOICE (
  INV_ID       INT IDENTITY(1,1) PRIMARY KEY,
  INV_NO       VARCHAR(20)   NOT NULL UNIQUE,         -- INV-00001
  CONTRACT_ID  INT           NOT NULL,
  CUST_ID      INT           NOT NULL,
  INV_DATE     DATE          NOT NULL,
  DUE_DATE     DATE          NULL,
  DESCRIPTION  NVARCHAR(500) NULL,
  AMOUNT       DECIMAL(18,2) NOT NULL DEFAULT 0,
  VAT_PRC      DECIMAL(5,2)  NOT NULL DEFAULT 5,
  VAT_AMT      DECIMAL(18,2) NOT NULL DEFAULT 0,
  TOTAL        DECIMAL(18,2) NOT NULL DEFAULT 0,
  PAID         DECIMAL(18,2) NOT NULL DEFAULT 0,      -- kept in step with AMC_PAYMENT
  STATUS       VARCHAR(10)   NOT NULL DEFAULT 'OPEN', -- OPEN | PAID | CANCELLED
  REMARK       NVARCHAR(500) NULL,
  USER_ID      INT           NULL,
  ENTRY_DATE   DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  EDIT_DATE    DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF OBJECT_ID('AMC_PAYMENT') IS NULL
CREATE TABLE AMC_PAYMENT (
  PAY_ID     INT IDENTITY(1,1) PRIMARY KEY,
  RCPT_NO    VARCHAR(20)   NOT NULL UNIQUE,           -- RCP-00001
  INV_ID     INT           NOT NULL,
  CUST_ID    INT           NOT NULL,
  PAY_DATE   DATE          NOT NULL,
  PAY_MODE   VARCHAR(10)   NOT NULL DEFAULT 'BANK',   -- CASH | BANK | CHEQUE | CARD
  REF_NO     NVARCHAR(60)  NULL,
  AMOUNT     DECIMAL(18,2) NOT NULL,
  REMARK     NVARCHAR(500) NULL,
  CANCELLED  BIT           NOT NULL DEFAULT 0,
  USER_ID    INT           NULL,
  ENTRY_DATE DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
