-- Support tickets with their note thread, and site visits.
IF OBJECT_ID('AMC_TICKET') IS NULL
CREATE TABLE AMC_TICKET (
  TICKET_ID     INT IDENTITY(1,1) PRIMARY KEY,
  TICKET_NO     VARCHAR(20)   NOT NULL UNIQUE,        -- TKT-00001
  CUST_ID       INT           NOT NULL,
  OPENED_AT     DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  CHANNEL       VARCHAR(10)   NOT NULL DEFAULT 'CALL',     -- CALL | WHATSAPP | EMAIL | VISIT
  TITLE         NVARCHAR(200) NOT NULL,
  DETAIL        NVARCHAR(MAX) NULL,
  PRIORITY      VARCHAR(10)   NOT NULL DEFAULT 'NORMAL',   -- LOW | NORMAL | HIGH | URGENT
  STATUS        VARCHAR(12)   NOT NULL DEFAULT 'OPEN',     -- OPEN | IN_PROGRESS | WAITING | CLOSED
  ASSIGNED_TO   INT           NULL,                   -- AMC_USER
  DUE_AT        DATETIME2     NULL,                   -- SLA deadline from the priority
  CLOSED_AT     DATETIME2     NULL,
  RESOLUTION    NVARCHAR(MAX) NULL,
  MINUTES_SPENT INT           NOT NULL DEFAULT 0,
  USER_ID       INT           NULL,
  EDIT_DATE     DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AMC_TICKET_STATUS') CREATE INDEX IX_AMC_TICKET_STATUS ON AMC_TICKET (STATUS, PRIORITY, OPENED_AT DESC);
GO
IF OBJECT_ID('AMC_TICKET_NOTE') IS NULL
CREATE TABLE AMC_TICKET_NOTE (
  NOTE_ID    INT IDENTITY(1,1) PRIMARY KEY,
  TICKET_ID  INT NOT NULL,
  USER_ID    INT NULL,
  NOTE       NVARCHAR(MAX) NOT NULL,
  MINUTES    INT NOT NULL DEFAULT 0,
  KIND       VARCHAR(10) NOT NULL DEFAULT 'NOTE',     -- NOTE | STATUS | ASSIGN | CLOSE
  ENTRY_DATE DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF OBJECT_ID('AMC_VISIT') IS NULL
CREATE TABLE AMC_VISIT (
  VISIT_ID   INT IDENTITY(1,1) PRIMARY KEY,
  CUST_ID    INT           NOT NULL,
  TICKET_ID  INT           NULL,
  VISIT_DATE DATE          NOT NULL,
  VISIT_TIME VARCHAR(5)    NULL,                      -- HH:MM
  ENGINEER   INT           NULL,                      -- AMC_USER
  PURPOSE    NVARCHAR(300) NOT NULL,
  STATUS     VARCHAR(10)   NOT NULL DEFAULT 'PLANNED',   -- PLANNED | DONE | CANCELLED
  MINUTES    INT           NOT NULL DEFAULT 0,
  TRAVEL_KM  DECIMAL(8,1)  NOT NULL DEFAULT 0,
  SIGNED_BY  NVARCHAR(100) NULL,
  REMARK     NVARCHAR(1000) NULL,
  USER_ID    INT           NULL,
  ENTRY_DATE DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  EDIT_DATE  DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AMC_VISIT_DATE') CREATE INDEX IX_AMC_VISIT_DATE ON AMC_VISIT (VISIT_DATE);
GO
