IF OBJECT_ID('BACKUP_LOG') IS NULL
CREATE TABLE BACKUP_LOG (BK_ID INT IDENTITY(1,1) PRIMARY KEY, KIND VARCHAR(10) NOT NULL, STATUS VARCHAR(10) NOT NULL DEFAULT 'RUNNING', FILE_PATH NVARCHAR(400) NULL, BYTES BIGINT NULL, DRIVE_STATUS VARCHAR(10) NULL, DRIVE_FILE_ID VARCHAR(100) NULL, ERROR_MSG NVARCHAR(1000) NULL, USER_ID INT NULL, START_TIME DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), END_TIME DATETIME2 NULL);
GO
