-- Party master: customers are added by hand (like the India AMC software) and may later be matched to a shop the ERP reports.
-- The link is one way: the ERP sends, DcAMC never sends anything back.
ALTER TABLE AMC_CUSTOMER ALTER COLUMN SERVER_ID INT NULL;
GO
IF EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = 'UX_AMC_CUSTOMER') ALTER TABLE AMC_CUSTOMER DROP CONSTRAINT UX_AMC_CUSTOMER;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_AMC_CUSTOMER_SERVER_SHOP') CREATE UNIQUE INDEX UX_AMC_CUSTOMER_SERVER_SHOP ON AMC_CUSTOMER (SERVER_ID, SHOP_CODE) WHERE SERVER_ID IS NOT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_AMC_CUSTOMER_HDD') CREATE UNIQUE INDEX UX_AMC_CUSTOMER_HDD ON AMC_CUSTOMER (HDD) WHERE HDD IS NOT NULL;
GO
IF COL_LENGTH('AMC_CUSTOMER', 'SOURCE') IS NULL ALTER TABLE AMC_CUSTOMER ADD
  SOURCE           VARCHAR(10)   NOT NULL DEFAULT 'MANUAL',   -- MANUAL (typed here) | ERP (arrived with a heartbeat)
  ADDRESS1         NVARCHAR(150) NULL,
  ADDRESS2         NVARCHAR(150) NULL,
  ADDRESS3         NVARCHAR(150) NULL,
  STATE_NAME       NVARCHAR(60)  NULL,
  CITY             NVARCHAR(60)  NULL,
  AREA             NVARCHAR(60)  NULL,
  PIN_CODE         VARCHAR(10)   NULL,
  PHONE_NO         VARCHAR(20)   NULL,
  TRN_NO           VARCHAR(20)   NULL,
  INSTALL_DATE     DATE          NULL,             -- the AMC year starts here
  BIRTH_DATE       DATE          NULL,
  INSTALL_AMT      DECIMAL(18,2) NOT NULL DEFAULT 0,
  CUST_TYPE        VARCHAR(12)   NOT NULL DEFAULT 'NEW',      -- NEW | EXISTING | CONVERTED
  REF_BY           NVARCHAR(100) NULL,
  OLD_HDD          VARCHAR(20)   NULL,
  OLD_INSTALL_DATE DATE          NULL,
  MAIN_PC_SERIAL   NVARCHAR(60)  NULL,
  LAN_PC_SERIAL1   NVARCHAR(60)  NULL,
  LAN_PC_SERIAL2   NVARCHAR(60)  NULL,
  REMARK           NVARCHAR(500) NULL;
GO
UPDATE AMC_CUSTOMER SET SOURCE = 'ERP' WHERE SERVER_ID IS NOT NULL AND SOURCE = 'MANUAL';
GO
-- invoices without a contract: the installation bill, and the difference when a shop moves up a software type
ALTER TABLE AMC_INVOICE ALTER COLUMN CONTRACT_ID INT NULL;
GO
IF COL_LENGTH('AMC_INVOICE', 'KIND') IS NULL ALTER TABLE AMC_INVOICE ADD KIND VARCHAR(10) NOT NULL DEFAULT 'AMC';   -- AMC | INSTALL | UPGRADE
GO
IF OBJECT_ID('AMC_PLAN_CHANGE') IS NULL
CREATE TABLE AMC_PLAN_CHANGE (
  CHANGE_ID   INT IDENTITY(1,1) PRIMARY KEY,
  CUST_ID     INT NOT NULL,
  FROM_PLAN   VARCHAR(20) NULL,
  TO_PLAN     VARCHAR(20) NOT NULL,
  CHANGE_DATE DATE NOT NULL,
  AMOUNT      DECIMAL(18,2) NOT NULL DEFAULT 0,   -- price of the new type minus the old one (the "convert amount")
  INV_ID      INT NULL,
  USER_ID     INT NULL,
  ENTRY_DATE  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
-- leads and their follow-ups (a small CRM)
IF OBJECT_ID('AMC_LEAD') IS NULL
CREATE TABLE AMC_LEAD (
  LEAD_ID      INT IDENTITY(1,1) PRIMARY KEY,
  NAME         NVARCHAR(150) NOT NULL,
  CONTACT_NAME NVARCHAR(100) NULL,
  MOBILE_NO    VARCHAR(20)   NULL,
  EMAIL_ID     NVARCHAR(150) NULL,
  CITY         NVARCHAR(60)  NULL,
  EMIRATE_CODE VARCHAR(3)    NULL,
  SOURCE       NVARCHAR(60)  NULL,             -- reference, call, exhibition, website…
  PLAN_CODE    VARCHAR(20)   NULL,             -- the software type they are looking at
  STAGE        VARCHAR(12)   NOT NULL DEFAULT 'NEW',   -- NEW | CONTACTED | DEMO | PROPOSAL | WON | LOST
  OWNER_ID     INT           NULL,             -- AMC_USER who follows it up
  NEXT_FOLLOW  DATETIME2     NULL,             -- next call / demo, Dubai time stored as UTC
  EST_AMT      DECIMAL(18,2) NOT NULL DEFAULT 0,
  NOTES        NVARCHAR(2000) NULL,
  CUST_ID      INT           NULL,             -- filled when won and made a party
  USER_ID      INT           NULL,
  ENTRY_DATE   DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  EDIT_DATE    DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF OBJECT_ID('AMC_LEAD_NOTE') IS NULL
CREATE TABLE AMC_LEAD_NOTE (NOTE_ID INT IDENTITY(1,1) PRIMARY KEY, LEAD_ID INT NOT NULL, USER_ID INT NULL, NOTE NVARCHAR(2000) NOT NULL, STAGE VARCHAR(12) NULL, NEXT_FOLLOW DATETIME2 NULL, ENTRY_DATE DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
-- notifications for the team: follow-ups due, demos, tickets past SLA, licences ending, and any the owner writes by hand
IF OBJECT_ID('AMC_NOTIFY') IS NULL
CREATE TABLE AMC_NOTIFY (
  NOTIFY_ID  INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID    INT           NULL,               -- null = everyone
  KIND       VARCHAR(12)   NOT NULL,           -- FOLLOWUP | DEMO | TICKET | LICENCE | AMC | CUSTOM
  TITLE      NVARCHAR(200) NOT NULL,
  BODY       NVARCHAR(1000) NULL,
  LINK       VARCHAR(200)  NULL,               -- where it opens in the app
  REF_KEY    VARCHAR(80)   NULL,               -- what it is about, so it is made once
  DUE_AT     DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  READ_AT    DATETIME2     NULL,
  BY_USER    INT           NULL,
  ENTRY_DATE DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AMC_NOTIFY_USER') CREATE INDEX IX_AMC_NOTIFY_USER ON AMC_NOTIFY (USER_ID, READ_AT, DUE_AT DESC);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_AMC_NOTIFY_REF') CREATE UNIQUE INDEX UX_AMC_NOTIFY_REF ON AMC_NOTIFY (REF_KEY, USER_ID) WHERE REF_KEY IS NOT NULL;
GO
