import { Router } from 'express';
import { requireAuth, noMoney } from '../middleware/auth.js';
import { wrap } from '../utils/httpError.js';
import { rq } from '../config/db.js';
import { expireContracts } from '../services/contractService.js';
/** The dashboard in one call: expiring / expired licences, AMCs, outstanding, open tickets by priority, offline servers, today's visits. */
const r = Router();
r.get('/dashboard', requireAuth, wrap(async (req, res) => {
  await expireContracts();
  const q = await (await rq()).query(`
    SELECT (SELECT COUNT(*) FROM AMC_CUSTOMER WHERE ACTIVE = 1) AS SHOPS,
      (SELECT COUNT(*) FROM AMC_CUSTOMER WHERE ACTIVE = 1 AND LIC_END BETWEEN CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE) AND DATEADD(day, 30, CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE))) AS LIC_30,
      (SELECT COUNT(*) FROM AMC_CUSTOMER WHERE ACTIVE = 1 AND LIC_END < CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE)) AS LIC_EXPIRED,
      (SELECT COUNT(*) FROM AMC_CONTRACT WHERE STATUS = 'LIVE') AS AMC_LIVE,
      (SELECT COUNT(*) FROM AMC_CONTRACT WHERE STATUS = 'LIVE' AND END_DATE <= DATEADD(day, 30, CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE))) AS AMC_30,
      (SELECT COUNT(*) FROM AMC_CUSTOMER C WHERE C.ACTIVE = 1 AND NOT EXISTS (SELECT 1 FROM AMC_CONTRACT K WHERE K.CUST_ID = C.CUST_ID AND K.STATUS = 'LIVE')) AS NO_AMC,
      (SELECT ISNULL(SUM(TOTAL - PAID), 0) FROM AMC_INVOICE WHERE STATUS = 'OPEN') AS OUTSTANDING,
      (SELECT ISNULL(SUM(TOTAL - PAID), 0) FROM AMC_INVOICE WHERE STATUS = 'OPEN' AND DUE_DATE < CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE)) AS OVERDUE,
      (SELECT COUNT(*) FROM AMC_SERVER WHERE ACTIVE = 1 AND (LAST_HEARTBEAT IS NULL OR LAST_HEARTBEAT < DATEADD(hour, -48, SYSUTCDATETIME()))) AS SERVERS_OFFLINE,
      (SELECT COUNT(*) FROM AMC_SERVER WHERE ACTIVE = 1) AS SERVERS,
      (SELECT COUNT(*) FROM AMC_TICKET WHERE STATUS <> 'CLOSED' AND DUE_AT < SYSUTCDATETIME()) AS TICKETS_LATE;
    SELECT PRIORITY, COUNT(*) AS N FROM AMC_TICKET WHERE STATUS <> 'CLOSED' GROUP BY PRIORITY;
    SELECT TOP 8 C.CUST_ID, C.SHOP_CODE, C.SHOP_NAME, C.CONTACT_NAME, C.MOBILE_NO, C.LIC_END, DATEDIFF(day, CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE), C.LIC_END) AS DAYS_LEFT, K.CONTRACT_NO AS AMC_NO FROM AMC_CUSTOMER C OUTER APPLY (SELECT TOP 1 CONTRACT_NO FROM AMC_CONTRACT X WHERE X.CUST_ID = C.CUST_ID AND X.STATUS = 'LIVE') K WHERE C.ACTIVE = 1 AND C.LIC_END IS NOT NULL AND DATEDIFF(day, CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE), C.LIC_END) <= 30 ORDER BY C.LIC_END;
    SELECT V.VISIT_ID, V.VISIT_TIME, V.PURPOSE, V.STATUS, C.CUST_ID, C.SHOP_NAME, E.USER_NAME AS ENGINEER_NAME FROM AMC_VISIT V JOIN AMC_CUSTOMER C ON C.CUST_ID = V.CUST_ID LEFT JOIN AMC_USER E ON E.USER_ID = V.ENGINEER WHERE V.VISIT_DATE = CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE) AND V.STATUS <> 'CANCELLED' ORDER BY V.VISIT_TIME;
    SELECT TOP 6 T.TICKET_ID, T.TICKET_NO, T.TITLE, T.PRIORITY, T.STATUS, T.DUE_AT, DATEDIFF(minute, SYSUTCDATETIME(), T.DUE_AT) AS MINUTES_TO_DUE, C.SHOP_NAME, A.USER_NAME AS ASSIGNED_NAME FROM AMC_TICKET T JOIN AMC_CUSTOMER C ON C.CUST_ID = T.CUST_ID LEFT JOIN AMC_USER A ON A.USER_ID = T.ASSIGNED_TO WHERE T.STATUS <> 'CLOSED' ORDER BY CASE T.PRIORITY WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END, T.DUE_AT;
    SELECT TOP 5 I.INV_ID, I.INV_NO, I.DUE_DATE, I.TOTAL - I.PAID AS BALANCE, C.CUST_ID, C.SHOP_NAME, DATEDIFF(day, I.DUE_DATE, CAST(DATEADD(hour, 4, SYSUTCDATETIME()) AS DATE)) AS DAYS_OVERDUE FROM AMC_INVOICE I JOIN AMC_CUSTOMER C ON C.CUST_ID = I.CUST_ID WHERE I.STATUS = 'OPEN' AND I.TOTAL - I.PAID > 0.004 ORDER BY I.DUE_DATE;
    SELECT S.SERVER_ID, S.SERVER_CODE, S.NAME, S.LAST_HEARTBEAT, (SELECT COUNT(*) FROM AMC_CUSTOMER C WHERE C.SERVER_ID = S.SERVER_ID AND C.ACTIVE = 1) AS SHOPS FROM AMC_SERVER S WHERE S.ACTIVE = 1 AND (S.LAST_HEARTBEAT IS NULL OR S.LAST_HEARTBEAT < DATEADD(hour, -48, SYSUTCDATETIME())) ORDER BY S.LAST_HEARTBEAT;
    SELECT TOP 8 A.LOG_TIME, A.TABLE_NAME, A.REC_KEY, A.ACTION, U.USER_NAME FROM AUDIT_LOG A LEFT JOIN AMC_USER U ON U.USER_ID = A.USER_ID WHERE A.ACTION <> 'HEARTBEAT' ORDER BY A.LOG_TIME DESC`);
  const [k] = q.recordsets[0]; const support = req.ctx.role === 'SUPPORT';
  res.json({ success: true, kpi: support ? { ...k, OUTSTANDING: null, OVERDUE: null } : k, byPriority: q.recordsets[1], expiring: q.recordsets[2], visitsToday: q.recordsets[3], tickets: q.recordsets[4], overdue: support ? [] : q.recordsets[5], offline: q.recordsets[6], activity: q.recordsets[7] });
}));
export default r;
