import { useId } from 'react';
import { Search, AlertTriangle } from 'lucide-react';
import { focusNext } from '../../lib/enterNav.js';
import { Modal } from './Modal.jsx';
import { Button } from './Button.jsx';
export function Toggle({ checked, onChange, label, hint, disabled }) {
  const id = useId();
  return <div className="flex items-start justify-between gap-4 py-1">{(label || hint) && <label htmlFor={id} className="cursor-pointer"><div className="text-[13.5px] font-medium">{label}</div>{hint && <div className="text-[12px] normal-case text-muted">{hint}</div>}</label>}<button id={id} type="button" role="switch" aria-checked={!!checked} disabled={disabled} className="toggle" data-nav data-nav-stay="true" title="Space = on / off · Enter = next field" onClick={() => onChange?.(!checked)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); e.stopPropagation(); const root = e.currentTarget.closest('form, [data-nav-root], main') || document; if (!focusNext(root, e.currentTarget)) e.currentTarget.closest('form')?.requestSubmit?.(); } }}><span className="toggle-knob" /></button></div>;
}
export function Segmented({ value, onChange, options, className = '' }) { return <div className={`seg ${className}`} role="tablist">{options.map((o) => <button key={o.value} type="button" role="tab" aria-selected={value === o.value} className={`seg-item ${value === o.value ? 'seg-item-active' : ''}`} onClick={() => onChange(o.value)}>{o.label}</button>)}</div>; }
export function Tabs({ value, onChange, tabs }) { return <div className="flex min-w-0 flex-1 gap-5 overflow-x-auto border-b border-line [scrollbar-width:none]" role="tablist">{tabs.map((t) => <button key={t.value} type="button" role="tab" aria-selected={value === t.value} className={`tab shrink-0 ${value === t.value ? 'tab-active' : ''}`} onClick={() => onChange(t.value)}>{t.label}{t.count != null && <span className={`ml-1.5 rounded-full px-1.5 text-[11px] ${value === t.value ? 'bg-accent/20 text-ink' : 'bg-surface-3 text-muted'}`}>{t.count}</span>}</button>)}</div>; }
export function Badge({ tone = 'muted', children, className = '' }) { const t = { muted: 'bg-surface-3 text-muted', ok: 'bg-ok/12 text-ok', warn: 'bg-warn/12 text-warn', bad: 'bg-bad/12 text-bad', info: 'bg-info/12 text-info', accent: 'bg-accent/15 text-ink' }[tone]; return <span className={`badge ${t} ${className}`}>{children}</span>; }
export function SearchBox({ value, onChange, placeholder = 'Search…', className = '', inputRef, autoFocus }) { return <div className={`relative ${className}`}><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" /><input ref={inputRef} autoFocus={autoFocus} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="input !pl-9 pr-9" data-nav-stay="true" /><kbd className="kbd absolute right-2.5 top-1/2 -translate-y-1/2">/</kbd></div>; }
export function PageHeader({ title, subtitle, actions, children }) { return <div className="mb-4 flex flex-wrap items-start justify-between gap-3 sm:flex-nowrap"><div className="min-w-[220px] flex-1 basis-[220px]"><h1 className="font-display text-[20px] font-bold tracking-tight">{title}</h1>{subtitle && <p className="mt-0.5 max-w-[92ch] text-[11.5px] leading-[1.45] tracking-[.01em] text-muted">{subtitle}</p>}{children}</div>{actions && <div className="flex w-full flex-wrap items-center gap-2 sm:w-auto sm:shrink-0 sm:pt-1">{actions}</div>}</div>; }
export function FormSection({ title, children, className = '' }) { return <section className={className}><div className="section-title">{title}</div><div className="field-grid">{children}</div></section>; }
export function Kpi({ label, value, icon: Icon, tone = '', onClick, sub }) { return <button type="button" onClick={onClick} className={`kpi flex items-center gap-3 !p-3 text-left ${onClick ? 'hover:border-accent/50' : 'cursor-default'}`}>{Icon && <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-accent/10"><Icon className={`h-4 w-4 ${tone || 'text-ink'}`} /></span>}<div className="min-w-0"><div className={`num text-[17px] font-semibold leading-tight ${tone}`}>{value}</div><div className="truncate text-[11.5px] text-muted">{label}</div>{sub && <div className="text-[11px] text-faint">{sub}</div>}</div></button>; }
export function ErrorBox({ error }) { return error ? <div className="mb-3 flex items-start gap-2 rounded-md border border-bad/30 bg-bad/10 px-3 py-2 text-[13px] normal-case"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-bad" />{error.message || String(error)}</div> : null; }
export function ConfirmDialog({ open, onClose, onConfirm, title = 'Are you sure?', message, hint, confirmLabel = 'Confirm', cancelLabel = 'Cancel', danger = true, busy, icon: Icon = AlertTriangle }) {
  const tone = danger ? 'bg-bad/12 text-bad ring-bad/25' : 'bg-accent/15 text-accent ring-accent/30';
  return <Modal open={open} onClose={busy ? undefined : onClose} title={title} size="sm" footer={<><Button variant="ghost" onClick={onClose} disabled={busy} className="!h-10 !px-4">{cancelLabel}</Button><Button variant={danger ? 'danger' : 'primary'} loading={busy} onClick={onConfirm} autoFocus className="!h-10 !px-5">{confirmLabel}</Button></>}>
    <div className="flex gap-4 py-1"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-full ring-1 ring-inset ${tone}`}><Icon className="h-5 w-5" /></div><div className="min-w-0 pt-0.5"><p className="text-[14px] normal-case leading-relaxed text-ink">{message}</p>{hint && <p className="mt-1.5 text-[12.5px] normal-case text-muted">{hint}</p>}</div></div>
  </Modal>;
}
