import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { reportService } from '../../services/amcService.js';
import { useQuery } from '../../hooks/useQuery.js';
import { useRights } from '../../app/AuthContext.jsx';
import { Dropdown } from '../../components/ui/Dropdown.jsx';
import { Badge, Segmented } from '../../components/ui/Controls.jsx';
import { ReportShell, Filter, DateFilter, periodLabel, startOfMonth, startOfYear, today } from './ReportShell.jsx';
import { formatDate, fmt, formatAED, displayMobile, formatDateTime } from '../../lib/fmt.js';
const sum = (rows, k) => (rows || []).reduce((a, r) => a + Number(r[k] || 0), 0);
const daysCell = (d) => d == null ? '' : <span className={d < 0 ? 'text-bad' : d <= 7 ? 'text-warn' : ''}>{d < 0 ? `${-d} over` : d}</span>;
const DAYS_OPTS = [['7', 'Next 7 days'], ['15', 'Next 15 days'], ['30', 'Next 30 days'], ['60', 'Next 60 days'], ['90', 'Next 90 days'], ['expired', 'Already expired']];

export function ExpiringLicencesPage() {
  const nav = useNavigate(); const [days, setDays] = useState('30'); const q = useQuery(() => reportService.get('expiring-licences', days === 'expired' ? { expired: '1' } : { days }), [days]); const rows = q.data?.rows || [];
  return <ReportShell title="Expiring licences" subtitle="ERP licences (from the heartbeat) ending soon, with the AMC on file and who to call." csvName="expiring-licences" loading={q.loading} error={q.error} rows={rows} rowKey="CUST_ID" onRow={(r) => nav(`/customers/${r.CUST_ID}`)} periodText={DAYS_OPTS.find((x) => x[0] === days)?.[1]}
    filters={<Filter label="Window"><Dropdown size="sm" className="w-44" value={days} onChange={(e) => setDays(e.target.value)} options={DAYS_OPTS} /></Filter>}
    kpis={[['Shops', rows.length], ['Without AMC', rows.filter((r) => !r.AMC_NO).length, 'warn'], ['Server offline', rows.filter((r) => r.OFFLINE).length, 'bad'], ['Tills covered', rows.reduce((a, r) => a + (Number(r.TILLS) || 0), 0)]]}
    columns={[{ key: 'SHOP_NAME', label: 'Shop' }, { key: 'SHOP_CODE', label: 'Shop ID' }, { key: 'HDD', label: 'Code' }, { key: 'PLAN_CODE', label: 'Version' }, { key: 'TILLS', label: 'Tills', align: 'center' }, { key: 'LIC_END', label: 'Licence ends', render: (r) => formatDate(r.LIC_END), csv: (r) => formatDate(r.LIC_END) }, { key: 'LIC_DAYS', label: 'Days', align: 'right', render: (r) => daysCell(r.LIC_DAYS) }, { key: 'AMC_NO', label: 'AMC', render: (r) => r.AMC_NO ? `${r.AMC_NO} · ${r.AMC_STATUS}` : <span className="text-warn">none</span> }, { key: 'AMC_END', label: 'AMC ends', render: (r) => formatDate(r.AMC_END), csv: (r) => formatDate(r.AMC_END) }, { key: 'CONTACT_NAME', label: 'Contact' }, { key: 'MOBILE_NO', label: 'Mobile', render: (r) => displayMobile(r.MOBILE_NO) }, { key: 'SERVER_NAME', label: 'Server', render: (r) => <span>{r.SERVER_NAME}{r.OFFLINE ? <Badge tone="bad" className="ml-1">offline</Badge> : null}</span>, csv: (r) => r.SERVER_NAME }]} />;
}
export function ExpiringAmcsPage() {
  const nav = useNavigate(); const { money } = useRights(); const [days, setDays] = useState('30'); const q = useQuery(() => reportService.get('expiring-amcs', days === 'expired' ? { expired: '1' } : { days }), [days]); const rows = q.data?.rows || [];
  return <ReportShell title="Expiring AMCs" subtitle="Live contracts ending soon and not yet renewed." csvName="expiring-amcs" loading={q.loading} error={q.error} rows={rows} rowKey="CONTRACT_ID" onRow={(r) => nav(`/customers/${r.CUST_ID}?tab=contracts`)} periodText={DAYS_OPTS.find((x) => x[0] === days)?.[1]}
    filters={<Filter label="Window"><Dropdown size="sm" className="w-44" value={days} onChange={(e) => setDays(e.target.value)} options={DAYS_OPTS} /></Filter>}
    kpis={[['Contracts', rows.length], ['Not renewed', rows.filter((r) => !r.RENEWED).length, 'warn'], ...(money ? [['Value', formatAED(sum(rows, 'TOTAL'))]] : [])]}
    columns={[{ key: 'CONTRACT_NO', label: 'Contract' }, { key: 'SHOP_NAME', label: 'Shop' }, { key: 'HDD', label: 'Code' }, { key: 'START_DATE', label: 'From', render: (r) => formatDate(r.START_DATE), csv: (r) => formatDate(r.START_DATE) }, { key: 'END_DATE', label: 'Ends', render: (r) => formatDate(r.END_DATE), csv: (r) => formatDate(r.END_DATE) }, { key: 'DAYS_LEFT', label: 'Days', align: 'right', render: (r) => daysCell(r.DAYS_LEFT) }, { key: 'RENEWED', label: 'Renewal', render: (r) => r.RENEWED ? <Badge tone="ok">made</Badge> : <Badge tone="warn">pending</Badge>, csv: (r) => (r.RENEWED ? 'made' : 'pending') }, ...(money ? [{ key: 'TOTAL', label: 'Value', align: 'right', render: (r) => fmt(r.TOTAL) }] : []), { key: 'CONTACT_NAME', label: 'Contact' }, { key: 'MOBILE_NO', label: 'Mobile', render: (r) => displayMobile(r.MOBILE_NO) }]}
    footer={money && <><td colSpan={7} className="r">Total</td><td className="r num">{fmt(sum(rows, 'TOTAL'))}</td><td colSpan={2} /></>} />;
}
export function OutstandingReportPage() {
  const nav = useNavigate(); const q = useQuery(() => reportService.get('outstanding'), []); const rows = q.data?.rows || [];
  return <ReportShell title="Outstanding" subtitle="Money due per customer across open invoices." csvName="outstanding" loading={q.loading} error={q.error} rows={rows} rowKey="CUST_ID" onRow={(r) => nav(`/customers/${r.CUST_ID}?tab=payments`)}
    kpis={[['Customers', rows.length], ['Invoices', sum(rows, 'INVOICES')], ['Due', formatAED(sum(rows, 'BALANCE')), 'bad'], ['Overdue', formatAED(sum(rows, 'OVERDUE')), 'warn']]}
    columns={[{ key: 'SHOP_NAME', label: 'Shop' }, { key: 'SHOP_CODE', label: 'Shop ID' }, { key: 'INVOICES', label: 'Invoices', align: 'center' }, { key: 'OLDEST_DUE', label: 'Oldest due', render: (r) => formatDate(r.OLDEST_DUE), csv: (r) => formatDate(r.OLDEST_DUE) }, { key: 'TOTAL', label: 'Invoiced', align: 'right', render: (r) => fmt(r.TOTAL) }, { key: 'PAID', label: 'Received', align: 'right', render: (r) => fmt(r.PAID) }, { key: 'BALANCE', label: 'Balance', align: 'right', render: (r) => <b>{fmt(r.BALANCE)}</b> }, { key: 'OVERDUE', label: 'Of which overdue', align: 'right', render: (r) => <span className={Number(r.OVERDUE) ? 'text-bad' : ''}>{fmt(r.OVERDUE)}</span> }, { key: 'CONTACT_NAME', label: 'Contact' }, { key: 'MOBILE_NO', label: 'Mobile', render: (r) => displayMobile(r.MOBILE_NO) }]}
    footer={<><td colSpan={4} className="r">Total</td><td className="r num">{fmt(sum(rows, 'TOTAL'))}</td><td className="r num">{fmt(sum(rows, 'PAID'))}</td><td className="r num">{fmt(sum(rows, 'BALANCE'))}</td><td className="r num">{fmt(sum(rows, 'OVERDUE'))}</td><td colSpan={2} /></>} />;
}
export function CollectionsPage() {
  const nav = useNavigate(); const [p, setP] = useState({ from: startOfMonth(), to: today() }); const q = useQuery(() => reportService.get('collections', p), [p]); const rows = q.data?.rows || [];
  const presets = [['month', 'This month'], ['year', 'This year']];
  return <ReportShell title="Collections" subtitle="Receipts in the period, by mode and by month, against what was invoiced." csvName="collections" loading={q.loading} error={q.error} rows={rows} rowKey="PAY_ID" onRow={(r) => nav(`/payments/${r.PAY_ID}/print`)} periodText={periodLabel(p.from, p.to)}
    filters={<><DateFilter label="From" value={p.from} onChange={(v) => setP({ ...p, from: v })} /><DateFilter label="To" value={p.to} onChange={(v) => setP({ ...p, to: v })} /><Filter label="Quick"><Segmented value="" onChange={(v) => setP(v === 'month' ? { from: startOfMonth(), to: today() } : { from: startOfYear(), to: today() })} options={presets.map(([value, label]) => ({ value, label }))} /></Filter></>}
    kpis={[['Received', formatAED(sum(rows, 'AMOUNT')), 'ok'], ['Receipts', rows.length], ['Invoiced in period', formatAED(q.data?.invoiced?.AMOUNT || 0)], ['Invoices raised', q.data?.invoiced?.N || 0]]}
    columns={[{ key: 'PAY_DATE', label: 'Date', render: (r) => formatDate(r.PAY_DATE), csv: (r) => formatDate(r.PAY_DATE) }, { key: 'RCPT_NO', label: 'Receipt' }, { key: 'SHOP_NAME', label: 'Shop' }, { key: 'INV_NO', label: 'Invoice' }, { key: 'PAY_MODE', label: 'Mode' }, { key: 'REF_NO', label: 'Ref' }, { key: 'AMOUNT', label: 'Amount', align: 'right', render: (r) => fmt(r.AMOUNT) }, { key: 'USER_NAME', label: 'By' }]}
    footer={<><td colSpan={6} className="r">Total</td><td className="r num">{fmt(sum(rows, 'AMOUNT'))}</td><td /></>}>
    {q.data && <div className="grid gap-3 md:grid-cols-2"><div className="rpt"><div className="px-3 pt-2.5 text-[13px] font-semibold">By mode</div><table><thead><tr><th>Mode</th><th className="c">Receipts</th><th className="r">Amount</th></tr></thead><tbody>{q.data.byMode.map((m) => <tr key={m.PAY_MODE}><td>{m.PAY_MODE}</td><td className="c">{m.N}</td><td className="r num">{fmt(m.AMOUNT)}</td></tr>)}</tbody></table></div><div className="rpt"><div className="px-3 pt-2.5 text-[13px] font-semibold">By month</div><table><thead><tr><th>Month</th><th className="c">Receipts</th><th className="r">Amount</th></tr></thead><tbody>{q.data.byMonth.map((m) => <tr key={m.MONTH}><td>{m.MONTH}</td><td className="c">{m.N}</td><td className="r num">{fmt(m.AMOUNT)}</td></tr>)}</tbody></table></div></div>}
  </ReportShell>;
}
export function TicketsReportPage() {
  const nav = useNavigate(); const [p, setP] = useState({ from: startOfYear(), to: today(), by: 'engineer' }); const q = useQuery(() => reportService.get('tickets', p), [p]); const rows = q.data?.rows || [];
  const eng = p.by === 'engineer';
  return <ReportShell title={eng ? 'Tickets by engineer' : 'Tickets by customer'} subtitle="Tickets opened in the period." csvName="tickets" loading={q.loading} error={q.error} rows={rows} rowKey="NAME" onRow={eng ? undefined : (r) => nav(`/customers/${r.CUST_ID}?tab=tickets`)} periodText={periodLabel(p.from, p.to)}
    filters={<><DateFilter label="From" value={p.from} onChange={(v) => setP({ ...p, from: v })} /><DateFilter label="To" value={p.to} onChange={(v) => setP({ ...p, to: v })} /><Filter label="Group by"><Segmented value={p.by} onChange={(v) => setP({ ...p, by: v })} options={[{ value: 'engineer', label: 'Engineer' }, { value: 'customer', label: 'Customer' }]} /></Filter></>}
    kpis={[['Tickets', sum(rows, 'N')], ['Closed', sum(rows, 'CLOSED'), 'ok'], ['Open', sum(rows, 'OPEN_N'), 'warn'], ['Minutes', sum(rows, 'MINUTES')]]}
    columns={eng ? [{ key: 'NAME', label: 'Engineer' }, { key: 'N', label: 'Tickets', align: 'center' }, { key: 'CLOSED', label: 'Closed', align: 'center' }, { key: 'OPEN_N', label: 'Open', align: 'center' }, { key: 'LATE', label: 'Closed late', align: 'center', render: (r) => <span className={Number(r.LATE) ? 'text-bad' : ''}>{r.LATE}</span> }, { key: 'MINUTES', label: 'Minutes', align: 'right' }, { key: 'AVG_MIN_TO_CLOSE', label: 'Avg hours to close', align: 'right', render: (r) => r.AVG_MIN_TO_CLOSE == null ? '' : (r.AVG_MIN_TO_CLOSE / 60).toFixed(1) }]
      : [{ key: 'NAME', label: 'Customer' }, { key: 'N', label: 'Tickets', align: 'center' }, { key: 'CLOSED', label: 'Closed', align: 'center' }, { key: 'OPEN_N', label: 'Open', align: 'center' }, { key: 'HIGH', label: 'High / urgent', align: 'center' }, { key: 'MINUTES', label: 'Minutes', align: 'right' }]} />;
}
export function VisitsReportPage() {
  const [p, setP] = useState({ from: startOfMonth(), to: today() }); const q = useQuery(() => reportService.get('visits', p), [p]); const rows = q.data?.rows || [];
  return <ReportShell title="Visits by engineer" subtitle="Site visits in the period, with minutes and kilometres." csvName="visits" loading={q.loading} error={q.error} rows={rows} rowKey="NAME" periodText={periodLabel(p.from, p.to)}
    filters={<><DateFilter label="From" value={p.from} onChange={(v) => setP({ ...p, from: v })} /><DateFilter label="To" value={p.to} onChange={(v) => setP({ ...p, to: v })} /></>}
    kpis={[['Visits', sum(rows, 'N')], ['Done', sum(rows, 'DONE'), 'ok'], ['Minutes on site', sum(rows, 'MINUTES')], ['Kilometres', sum(rows, 'KM').toFixed(1)]]}
    columns={[{ key: 'NAME', label: 'Engineer' }, { key: 'N', label: 'Visits', align: 'center' }, { key: 'DONE', label: 'Done', align: 'center' }, { key: 'PLANNED', label: 'Planned', align: 'center' }, { key: 'CANCELLED', label: 'Cancelled', align: 'center' }, { key: 'SHOPS', label: 'Shops', align: 'center' }, { key: 'MINUTES', label: 'Minutes', align: 'right' }, { key: 'KM', label: 'Km', align: 'right', render: (r) => Number(r.KM || 0).toFixed(1) }]}>
    {q.data && <div className="rpt"><div className="px-3 pt-2.5 text-[13px] font-semibold">Every visit</div><table><thead><tr><th>Date</th><th>Shop</th><th>Engineer</th><th>Purpose</th><th>Ticket</th><th>Status</th><th className="r">Min</th><th className="r">Km</th></tr></thead><tbody>{q.data.visits.map((v) => <tr key={v.VISIT_ID}><td className="num">{formatDate(v.VISIT_DATE)}{v.VISIT_TIME ? ` ${v.VISIT_TIME}` : ''}</td><td>{v.SHOP_NAME}</td><td>{v.ENGINEER_NAME || '—'}</td><td className="normal-case">{v.PURPOSE}</td><td>{v.TICKET_NO || ''}</td><td>{v.STATUS}</td><td className="r num">{v.MINUTES}</td><td className="r num">{Number(v.TRAVEL_KM || 0).toFixed(1)}</td></tr>)}</tbody></table></div>}
  </ReportShell>;
}
export function CustomerHistoryPage() {
  const nav = useNavigate(); const { money } = useRights(); const [id, setId] = useState(''); const custs = useQuery(() => import('../../services/amcService.js').then((m) => m.customerService.list({ active: '' })), []);
  const q = useQuery(() => import('../../services/amcService.js').then((m) => m.customerService.history(id)), [id], { enabled: !!id }); const rows = q.data?.rows || [];
  const c = (custs.data?.rows || []).find((x) => String(x.CUST_ID) === String(id));
  return <ReportShell title="Customer history" subtitle="Everything on record for one shop: contracts, invoices, receipts, tickets, visits and reminders." csvName={`history-${c?.SHOP_CODE || ''}`} loading={q.loading} error={q.error} rows={id ? rows : null} rowKey={(r, i) => i} periodText={c ? `${c.SHOP_NAME} · ${c.SHOP_CODE}` : ''}
    filters={<Filter label="Shop" className="w-full sm:w-96"><Dropdown size="sm" value={id} onChange={(e) => setId(e.target.value)} options={[['', 'Choose the shop…'], ...(custs.data?.rows || []).map((x) => ({ value: String(x.CUST_ID), label: `${x.SHOP_NAME} (${x.SHOP_CODE})`, hint: x.HDD }))]} /></Filter>}
    kpis={id ? [['Contracts', rows.filter((r) => r.KIND === 'CONTRACT').length], ['Tickets', rows.filter((r) => r.KIND === 'TICKET').length], ['Visits', rows.filter((r) => r.KIND === 'VISIT').length], ...(money ? [['Received', formatAED(rows.filter((r) => r.KIND === 'PAYMENT').reduce((a, r) => a + Number(r.AMOUNT || 0), 0))]] : [['Reminders', rows.filter((r) => r.KIND === 'REMINDER').length]])] : null}
    columns={id ? [{ key: 'D', label: 'Date', render: (r) => formatDate(r.D), csv: (r) => formatDate(r.D) }, { key: 'KIND', label: 'What' }, { key: 'REF', label: 'Ref' }, { key: 'TEXT', label: 'Detail', className: 'normal-case' }, ...(money ? [{ key: 'AMOUNT', label: 'Amount', align: 'right', render: (r) => (r.AMOUNT != null ? fmt(r.AMOUNT) : '') }] : [])] : null}>
    {c && <div className="no-print text-[12.5px] text-muted"><button className="text-accent hover:underline" onClick={() => nav(`/customers/${c.CUST_ID}`)}>Open {c.SHOP_NAME}</button></div>}
  </ReportShell>;
}
