import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Plus, Target, PhoneCall, CalendarClock, Trophy, X, Send, UserPlus, Trash2, LayoutList, Columns3 } from 'lucide-react';
import { leadService } from '../../services/amcService.js';
import { useQuery, useDebounce } from '../../hooks/useQuery.js';
import { useHotkeys } from '../../hooks/useHotkeys.js';
import { useEnterNavigation } from '../../hooks/useEnterNavigation.js';
import { useRights, useAuth } from '../../app/AuthContext.jsx';
import { useTeam } from '../tickets/TicketDialogs.jsx';
import { Input, Select, Textarea } from '../../components/ui/Field.jsx';
import { Button } from '../../components/ui/Button.jsx';
import { Modal } from '../../components/ui/Modal.jsx';
import { useToast } from '../../components/ui/Toast.jsx';
import { PageHeader, Badge, Kpi, ErrorBox, SearchBox, Segmented, ConfirmDialog } from '../../components/ui/Controls.jsx';
import { Dropdown } from '../../components/ui/Dropdown.jsx';
import { DataTable } from '../../components/ui/DataTable.jsx';
import { formatDateTime, rel, displayMobile, initials, fmt } from '../../lib/fmt.js';

const STAGES = [['NEW', 'New'], ['CONTACTED', 'Contacted'], ['DEMO', 'Demo'], ['PROPOSAL', 'Proposal'], ['WON', 'Won'], ['LOST', 'Lost']];
const TONE = { NEW: 'muted', CONTACTED: 'info', DEMO: 'accent', PROPOSAL: 'warn', WON: 'ok', LOST: 'bad' };
const PLANS = [['', '—'], ['BASIC', 'Basic'], ['PRO', 'Pro'], ['ADVANCE', 'Advance'], ['ENTERPRISE', 'Enterprise']];
const EMIRATES = [['', '—'], ['DXB', 'Dubai'], ['AUH', 'Abu Dhabi'], ['SHJ', 'Sharjah'], ['AJM', 'Ajman'], ['RAK', 'Ras Al Khaimah'], ['FUJ', 'Fujairah'], ['UAQ', 'Umm Al Quwain']];
const local = (iso) => (iso ? new Date(new Date(iso).getTime() + 4 * 3600e3).toISOString().slice(0, 16) : '');   // Dubai wall time for <input type=datetime-local>
const fromLocal = (s) => (s ? new Date(new Date(`${s}:00Z`).getTime() - 4 * 3600e3).toISOString() : null);
const Stage = ({ s }) => <Badge tone={TONE[s]}>{STAGES.find((x) => x[0] === s)?.[1] || s}</Badge>;
const Next = ({ l }) => !l.NEXT_FOLLOW ? <span className="text-faint">—</span> : <span className={`num whitespace-nowrap ${l.OVERDUE ? 'text-bad' : ''}`}>{formatDateTime(l.NEXT_FOLLOW)}{l.OVERDUE ? ' · due' : ''}</span>;

/** Leads & follow-up — a small CRM: a lead per prospect, its stage, its owner, the next call or demo, and every follow-up noted. Won makes the party. */
export function LeadsPage() {
  const nav = useNavigate(); const toast = useToast(); const { support } = useRights(); const { session } = useAuth(); const team = useTeam(); const [sp, setSp] = useSearchParams();
  const [q, setQ] = useState(''); const dq = useDebounce(q); const [f, setF] = useState({ stage: '', owner: '', open: '1' }); const [view, setView] = useState(() => localStorage.getItem('dcamc.leads.view') || 'list');
  const list = useQuery(() => leadService.list({ q: dq, ...f }), [dq, f]); const rows = list.data?.rows || [];
  const [edit, setEdit] = useState(null); const [openId, setOpenId] = useState(sp.get('open') ? Number(sp.get('open')) : null); const [lead, setLead] = useState(null); const [fu, setFu] = useState({ NOTE: '', STAGE: '', NEXT_FOLLOW: '' }); const [busy, setBusy] = useState(''); const [ask, setAsk] = useState(null);
  useHotkeys({ 'alt+n': () => support && setEdit({ NAME: '', CONTACT_NAME: '', MOBILE_NO: '', EMAIL_ID: '', CITY: '', EMIRATE_CODE: 'DXB', SOURCE: '', PLAN_CODE: '', STAGE: 'NEW', OWNER_ID: String(session?.user?.USER_ID || ''), NEXT_FOLLOW: '', EST_AMT: '', NOTES: '' }) }, [support]);
  const load = async (id) => { try { const r = await leadService.get(id); setLead(r.lead); setFu({ NOTE: '', STAGE: r.lead.STAGE, NEXT_FOLLOW: '' }); } catch (e) { toast(e.message, 'error'); setOpenId(null); } };
  useEffect(() => { if (openId) load(openId); else setLead(null); }, [openId]); // eslint-disable-line
  const save = async () => { setBusy('save'); try { const body = { ...edit, NEXT_FOLLOW: fromLocal(edit.NEXT_FOLLOW) }; const r = edit.LEAD_ID ? await leadService.update(edit.LEAD_ID, body) : await leadService.create(body); toast(edit.LEAD_ID ? 'Lead saved' : `${r.lead.NAME} added`, 'success'); setEdit(null); list.refetch(); if (lead && r.lead.LEAD_ID === lead.LEAD_ID) setLead(r.lead); } catch (e) { toast(e.message, e.code === 'VALIDATION' ? 'warn' : 'error'); } finally { setBusy(''); } };
  const followUp = async () => { if (!fu.NOTE.trim()) return; setBusy('fu'); try { const r = await leadService.followUp(lead.LEAD_ID, { ...fu, NEXT_FOLLOW: fromLocal(fu.NEXT_FOLLOW) }); setLead(r.lead); setFu({ NOTE: '', STAGE: r.lead.STAGE, NEXT_FOLLOW: '' }); list.refetch(); toast('Follow-up noted', 'success'); } catch (e) { toast(e.message, 'warn'); } finally { setBusy(''); } };
  const won = async () => { setBusy('won'); try { const r = await leadService.convert(lead.LEAD_ID); toast(`${lead.NAME} is now a party`, 'success', 5000); list.refetch(); setOpenId(null); if (r.customer) nav('/customers'); } catch (e) { toast(e.message, 'error'); } finally { setBusy(''); } };
  const remove = async () => { try { await leadService.remove(ask.LEAD_ID); toast('Lead removed', 'success'); setAsk(null); setOpenId(null); list.refetch(); } catch (e) { toast(e.message, 'error'); } };
  const { formRef, onKeyDown } = useEnterNavigation({ onSubmit: save, onEscape: () => setEdit(null) }); const set = (k) => (e) => setEdit((s) => ({ ...s, [k]: e.target.value }));
  const setView2 = (v) => { setView(v); localStorage.setItem('dcamc.leads.view', v); };
  const open = rows.filter((l) => !['WON', 'LOST'].includes(l.STAGE));
  return <div className="w-full">
    <PageHeader title="Leads & follow-up" subtitle="Every prospect: stage, who follows it up, the next call or demo, and what was said each time. The bell reminds the owner when a follow-up or demo is due. Won turns the lead into a party." actions={<><Segmented value={view} onChange={setView2} options={[{ value: 'list', label: <LayoutList className="h-4 w-4" /> }, { value: 'board', label: <Columns3 className="h-4 w-4" /> }]} />{support && <Button icon={Plus} onClick={() => setEdit({ NAME: '', CONTACT_NAME: '', MOBILE_NO: '', EMAIL_ID: '', CITY: '', EMIRATE_CODE: 'DXB', SOURCE: '', PLAN_CODE: '', STAGE: 'NEW', OWNER_ID: String(session?.user?.USER_ID || ''), NEXT_FOLLOW: '', EST_AMT: '', NOTES: '' })} title="Alt+N">New lead</Button>}</>} />
    <div className="mb-3 grid gap-2 sm:grid-cols-4"><Kpi label="Open leads" value={open.length} icon={Target} /><Kpi label="Follow-ups due" value={open.filter((l) => l.OVERDUE).length} icon={PhoneCall} tone="text-bad" /><Kpi label="Demos" value={open.filter((l) => l.STAGE === 'DEMO').length} icon={CalendarClock} tone="text-info" onClick={() => setF({ ...f, stage: 'DEMO' })} /><Kpi label="Won" value={rows.filter((l) => l.STAGE === 'WON').length} icon={Trophy} tone="text-ok" onClick={() => setF({ ...f, stage: 'WON', open: '' })} /></div>
    <div className="mb-3 flex flex-wrap items-center gap-2"><SearchBox value={q} onChange={setQ} placeholder="Name, contact, mobile, city, source…" className="w-full sm:w-72" /><Dropdown size="sm" className="w-36" value={f.stage} onChange={(e) => setF({ ...f, stage: e.target.value, open: e.target.value ? '' : '1' })} options={[['', 'Any stage'], ...STAGES]} /><Dropdown size="sm" className="w-40" value={f.owner} onChange={(e) => setF({ ...f, owner: e.target.value })} options={[['', 'Anyone'], ...team.map((u) => [String(u.USER_ID), u.USER_NAME])]} /><label className="flex items-center gap-1.5 text-[12.5px] text-muted"><input type="checkbox" className="accent-[rgb(var(--accent))]" checked={f.open === '1' && !f.stage} onChange={(e) => setF({ ...f, open: e.target.checked ? '1' : '', stage: '' })} />Open only</label></div>
    <ErrorBox error={list.error} />
    {view === 'list' ? <DataTable rows={rows} loading={list.loading} rowKey="LEAD_ID" onRowClick={(l) => setOpenId(l.LEAD_ID)} columns={[
      { key: 'NAME', label: 'Lead', primary: true, render: (l) => <div><div className="font-medium">{l.NAME}</div><div className="text-[11.5px] text-muted">{l.CONTACT_NAME || '—'}{l.MOBILE_NO ? ` · ${displayMobile(l.MOBILE_NO)}` : ''}{l.CITY ? ` · ${l.CITY}` : ''}</div></div> },
      { key: 'STAGE', label: 'Stage', render: (l) => <Stage s={l.STAGE} /> }, { key: 'PLAN_CODE', label: 'Type', hideBelow: 'lg', render: (l) => l.PLAN_CODE || '—' }, { key: 'SOURCE', label: 'Source', hideBelow: 'lg', render: (l) => l.SOURCE || '—' },
      { key: 'OWNER_NAME', label: 'Owner', render: (l) => l.OWNER_NAME ? <span className="inline-flex items-center gap-1.5"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-accent/15 text-[10px] font-semibold">{initials(l.OWNER_NAME)}</span>{l.OWNER_NAME}</span> : <span className="text-faint">—</span> },
      { key: 'NEXT_FOLLOW', label: 'Next follow-up', render: (l) => <Next l={l} /> }, { key: 'LAST_FOLLOW', label: 'Last', hideBelow: 'xl', render: (l) => <span className="text-muted">{l.LAST_FOLLOW ? rel(l.LAST_FOLLOW) : 'never'}</span> }, { key: 'FOLLOWUPS', label: 'Notes', align: 'center', hideBelow: 'xl' },
    ]} emptyTitle="No leads" emptyHint="Every enquiry goes here — Alt+N." footer={<span>{rows.length} leads</span>} />
    : <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{STAGES.map(([s, l]) => { const col = rows.filter((x) => x.STAGE === s); return <div key={s} className="card flex flex-col"><div className="flex items-center justify-between border-b border-line px-3 py-2"><span className="text-[12px] font-semibold uppercase tracking-wide text-muted">{l}</span><span className="badge bg-surface-3 text-muted">{col.length}</span></div><div className="flex-1 space-y-2 p-2">{col.map((x) => <button key={x.LEAD_ID} onClick={() => setOpenId(x.LEAD_ID)} className={`w-full rounded-md border border-line bg-surface-2/40 p-2.5 text-left transition hover:border-accent/50 ${x.OVERDUE ? 'border-l-2 border-l-bad' : ''}`}><div className="text-[13px] font-medium leading-snug">{x.NAME}</div><div className="mt-0.5 text-[11.5px] text-muted">{x.CONTACT_NAME || '—'}{x.PLAN_CODE ? ` · ${x.PLAN_CODE}` : ''}</div><div className="mt-1.5 flex items-center justify-between text-[11px]"><Next l={x} />{x.OWNER_NAME && <span className="flex h-5 w-5 items-center justify-center rounded-full bg-accent/15 text-[9.5px] font-semibold" title={x.OWNER_NAME}>{initials(x.OWNER_NAME)}</span>}</div></button>)}{!col.length && <div className="py-4 text-center text-[12px] text-faint">—</div>}</div></div>; })}</div>}
    {/* editor */}
    <Modal open={!!edit} onClose={() => setEdit(null)} title={edit?.LEAD_ID ? `Edit · ${edit.NAME}` : 'New lead'} size="lg" footer={<><Button variant="ghost" onClick={() => setEdit(null)}>Cancel</Button><Button loading={busy === 'save'} onClick={save}>Save</Button></>}>
      {edit && <form ref={formRef} onKeyDown={onKeyDown} onSubmit={(e) => { e.preventDefault(); save(); }} className="grid gap-3 sm:grid-cols-2" noValidate>
        <Input label="Shop / person" className="sm:col-span-2" autoFocus {...{ value: edit.NAME, onChange: set('NAME') }} /><Input label="Contact person" value={edit.CONTACT_NAME} onChange={set('CONTACT_NAME')} /><Input label="Mobile" type="tel" upper={false} value={edit.MOBILE_NO} onChange={set('MOBILE_NO')} />
        <Input label="E-mail" type="email" value={edit.EMAIL_ID} onChange={set('EMAIL_ID')} /><Input label="City" value={edit.CITY} onChange={set('CITY')} /><Select label="Emirate" options={EMIRATES} value={edit.EMIRATE_CODE} onChange={set('EMIRATE_CODE')} /><Input label="Source" value={edit.SOURCE} onChange={set('SOURCE')} placeholder="Reference, call, exhibition…" />
        <Select label="Software type" options={PLANS} value={edit.PLAN_CODE} onChange={set('PLAN_CODE')} /><Select label="Stage" options={STAGES} value={edit.STAGE} onChange={set('STAGE')} /><Select label="Followed up by" options={[['', '—'], ...team.map((u) => [String(u.USER_ID), u.USER_NAME])]} value={edit.OWNER_ID} onChange={set('OWNER_ID')} />
        <Input label={edit.STAGE === 'DEMO' ? 'Demo at' : 'Next follow-up'} type="datetime-local" value={edit.NEXT_FOLLOW} onChange={set('NEXT_FOLLOW')} /><Input label="Expected amount (AED)" type="number" step="0.01" min="0" className="[&_input]:num [&_input]:text-right" value={edit.EST_AMT} onChange={set('EST_AMT')} /><Textarea label="Notes" className="sm:col-span-2" rows={3} value={edit.NOTES} onChange={set('NOTES')} />
      </form>}
    </Modal>
    {/* drawer */}
    {openId && <div className="fixed inset-0 z-50 flex justify-end bg-black/45 backdrop-blur-[2px] anim-fade" onMouseDown={(e) => e.target === e.currentTarget && setOpenId(null)}>
      <aside role="dialog" aria-modal="true" className="flex h-full w-full max-w-2xl flex-col bg-surface shadow-pop anim-slide-in">
        {!lead ? <div className="p-8 text-center text-muted">Opening…</div> : <>
          <header className="flex items-start justify-between gap-3 border-b border-line px-5 py-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Stage s={lead.STAGE} />{lead.PLAN_CODE && <Badge tone="accent">{lead.PLAN_CODE}</Badge>}{Number(lead.EST_AMT) > 0 && <span className="num text-[12px] text-muted">AED {fmt(lead.EST_AMT)}</span>}</div><h2 className="mt-1 truncate font-display text-[16px] font-bold">{lead.NAME}</h2><div className="text-[12px] text-muted">{lead.CONTACT_NAME || '—'}{lead.MOBILE_NO && <> · <a className="num text-accent hover:underline" href={`https://wa.me/${lead.MOBILE_NO}`} target="_blank" rel="noreferrer">{displayMobile(lead.MOBILE_NO)}</a></>}{lead.EMAIL_ID ? ` · ${lead.EMAIL_ID}` : ''}{lead.CITY ? ` · ${lead.CITY}` : ''} · source {lead.SOURCE || '—'} · owner {lead.OWNER_NAME || '—'} · next <Next l={lead} /></div></div><button onClick={() => setOpenId(null)} className="-mr-2 rounded-lg p-2 text-muted hover:bg-surface-2 hover:text-ink" aria-label="Close"><X className="h-5 w-5" /></button></header>
          <div className="min-h-0 flex-1 overflow-y-auto px-5 py-4">{lead.NOTES && <div className="mb-4 rounded-md border border-line bg-surface-2/40 px-3 py-2 text-[13px] normal-case">{lead.NOTES}</div>}<div className="section-title">Follow-ups</div><ol className="space-y-2">{lead.notes.map((n) => <li key={n.NOTE_ID} className="flex gap-3"><span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent/15 text-[10.5px] font-semibold">{initials(n.USER_NAME)}</span><div className="min-w-0 flex-1 rounded-md border border-line bg-surface-2/40 px-3 py-2"><div className="flex flex-wrap items-center gap-2 text-[11.5px] text-muted"><span className="font-medium text-ink">{n.USER_NAME || 'System'}</span><span title={formatDateTime(n.ENTRY_DATE)}>{rel(n.ENTRY_DATE)}</span>{n.STAGE && <Stage s={n.STAGE} />}{n.NEXT_FOLLOW && <span>next {formatDateTime(n.NEXT_FOLLOW)}</span>}</div><div className="mt-0.5 whitespace-pre-wrap text-[13px] normal-case">{n.NOTE}</div></div></li>)}{!lead.notes.length && <li className="text-[12.5px] text-faint">No follow-ups yet.</li>}</ol></div>
          {support && <footer className="space-y-2 border-t border-line bg-surface-2/60 px-5 py-3">{!['WON', 'LOST'].includes(lead.STAGE) ? <><Textarea rows={2} value={fu.NOTE} onChange={(e) => setFu({ ...fu, NOTE: e.target.value })} placeholder="What happened on this call / visit… (Ctrl+Enter saves)" onKeyDown={(e) => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); followUp(); } }} nav={false} /><div className="flex flex-wrap items-center gap-2"><Select value={fu.STAGE} onChange={(e) => setFu({ ...fu, STAGE: e.target.value })} options={STAGES} className="w-36" nav={false} /><Input type="datetime-local" value={fu.NEXT_FOLLOW} onChange={(e) => setFu({ ...fu, NEXT_FOLLOW: e.target.value })} className="w-52" nav={false} title="Next follow-up / demo" /><Button variant="soft" icon={Send} loading={busy === 'fu'} onClick={followUp} disabled={!fu.NOTE.trim()}>Note follow-up</Button><span className="flex-1" /><Button variant="ghost" onClick={() => setEdit({ ...lead, OWNER_ID: lead.OWNER_ID ? String(lead.OWNER_ID) : '', NEXT_FOLLOW: local(lead.NEXT_FOLLOW), EST_AMT: lead.EST_AMT || '', NOTES: lead.NOTES || '', PLAN_CODE: lead.PLAN_CODE || '', EMIRATE_CODE: lead.EMIRATE_CODE || '', SOURCE: lead.SOURCE || '', CITY: lead.CITY || '', EMAIL_ID: lead.EMAIL_ID || '', MOBILE_NO: lead.MOBILE_NO || '', CONTACT_NAME: lead.CONTACT_NAME || '' })}>Edit</Button><Button icon={UserPlus} loading={busy === 'won'} onClick={won} title="Mark won and make the party">Won → party</Button></div></> : <div className="flex items-center justify-between"><span className="text-[12.5px] text-muted">{lead.STAGE === 'WON' ? (lead.CUST_ID ? 'Won — party made.' : 'Won.') : 'Lost.'}</span><div className="flex gap-2">{lead.CUST_ID && <Button variant="ghost" onClick={() => nav(`/customers/${lead.CUST_ID}`)}>Open party</Button>}<Button variant="ghost" icon={Trash2} className="!text-bad" onClick={() => setAsk(lead)}>Remove</Button></div></div>}</footer>}
        </>}
      </aside>
    </div>}
    <ConfirmDialog open={!!ask} onClose={() => setAsk(null)} onConfirm={remove} title={`Remove ${ask?.NAME}?`} message="The lead and its follow-ups are deleted." confirmLabel="Remove" />
  </div>;
}
